#!/bin/bash
help() {
	echo 'kdsy-stat [OPTIONS]'
	echo '从本地数据库中读取登录数据并生成统计图'
	echo -e '\e[1mOPTIONS:\e[0m'
	echo '	-f:	指定本地数据库文件，不指定则使用默认数据库'
	echo '	-l|r:	指定时间区间上下界限，只接受 UNIX 时间戳'
	echo '	-p:	指定时间区间长度，单位为秒'
	echo '	-m:	指定用于显示条形图的单位长度'
	echo '	-v:	verbose (详细模式)，将输出额外信息和每个区间的登录用户统计表'
	echo '本程序不会向云端发起请求，因此可能缺失最新数据，请运行 kdsy-gather 手动更新。'
	exit
}

while getopts 'f:l:r:p:m:vh' opt ;do
	case $opt in
		f) db=$OPTARG ;;
		l) l=$OPTARG ;;
		r) r=$OPTARG ;;
		p) p=$OPTARG ;;
		m) m=$OPTARG ;;
		v) v=true ;;
		h) help ;;
		?) help ;;
	esac
done
shift $((OPTIND-1))

if [[ -z $db ]] ;then
	db=$KDSY/kdsy.db
fi
if [[ ! -f $db ]] ;then
	echo -e '\e[31m数据库不存在，请先运行 kdsy-gather 初始化数据库并收集信息\e[0m'
	exit
fi

# Right limit
if [[ -z $r ]] ;then
	r=$((`date +%s`+1800))	# UNIX timestamp now
	(( r = r - ( r % 1800 ) ))
fi
# Left limit
if [[ -z $l ]] ;then
	l=$((r-86400))			# 24 hours before now
fi
# Period
if [[ -z $p ]] ;then
	p=1800					# Half an hour
fi
# Multiply length
if [[ -z $m ]] ;then
	m=2
fi

# debug
if [[ ! -z $v ]] ;then
	echo '当前时间: '`date -Is -d@$l`'  '`date -Is -d@$r`
	echo '区间长度: '$p' 秒, 直方图长度倍率: '$m
fi

cur=$l
cnt=0
pbar() {
	lstr=`date -Im -d@$((cur-p)) |sed -e's/\+.*//' -e's/.*T//'`
	rstr=`date -Im -d@$cur |sed -e's/\+.*//' -e's/.*T//'`
	hr=`echo $lstr |sed -e's/:.*//' -e's/^0//'`
	if ((hr<7)) ;then
		if [[ -z $flag ]] ;then
			echo -e '\e[34m'`date -Id -d@$cur`'\e[0m'
			flag=1
		fi
		return
	fi
	echo -e -n $lstr' - '$rstr' '
	if (($cnt < 10)) ;then
		color='\e[32m'							# 1-9	Green
	elif (($cnt >= 10)) && (($cnt < 20)) ;then
		color='\e[33m'							# 10-19	Yellow
	else
		color='\e[31m'							# 20+	Red
	fi
	echo -n -e $color

	for j in `seq 1 $((cnt*m))` ;do
		echo -n '▇'
	done

	echo -e '\e[0m '$cnt						# End
}

echo -e '\e[34m'`date -Id -d@$cur`'\e[0m'
for i in `seq 1 $(( (r - l) / p ))` ;do
	cur=$((cur+p))
	cnt=`sqlite3 $db 'SELECT COUNT(1) FROM LOGIN WHERE ACCESS > '$((cur-p))' AND ACCESS < '$cur`
	if [[ ! -z $v ]] ;then
		sqlite3 $db -box 'SELECT * FROM LOGIN WHERE ACCESS > '$((cur-p))' AND ACCESS < '$cur' ORDER BY ACCESS'
	fi
	pbar
done
if [[ ! -z $v ]] ;then
	echo -n '区间内总登录数: '
	sqlite3 $db 'SELECT COUNT(1) FROM LOGIN WHERE ACCESS > '$l' AND ACCESS < '$r
	echo '数据库每半小时自动更新一次，最近半小时信息缺失属于正常情况，可手动更新'
fi

