#!/bin/bash

fhelp() {
	echo 'sksctl SUBCOMMAND [ARGS]'
	echo '高新西区校园网CLI套件'
	echo 'SUBCOMMAND'
	echo '	help		显示本帮助'
	echo '	usrinfo		查询用户账号信息'
	echo '	bindinfo	精确查询设备绑定信息'
	echo '	gather		立即收集一次绕过认证统计数据'
	echo '	stat		根据本地统计数据生成统计图'
	echo '	writelist	写入黑白名单'
	echo '	license		查看开源许可证'
	echo '	logcat		查看绕过认证数据收集日志'
	echo '请自行输入命令加 -h 查看具体用法, 例如 sksctl usrinfo -h'
	echo '本脚本以 AGPLv3 许可证开源'
	exit
}

if [[ -z $1 || $1 == 'help' ]] ;then
	fhelp
elif [[ $1 == 'license' ]] ;then
	cat $KDSY/LICENSE|less
elif [[ $1 == 'logcat' ]] ;then
	cat $KDSY/gather.log|less
else
	f=$1; shift 1
	$KDSY/bin/kdsy-$f $@
fi
